// <auto-generated />
namespace Restaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class createTabels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createTabels));
        
        string IMigrationMetadata.Id
        {
            get { return "202408261230099_createTabels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
